import { Customer, CustomerStatusType } from "@/types/customers";

export const DEFAULT_CUSTOMERS: Customer[] = [
  {
    id: "1",
    customerId: "KH001",
    name: "Công Ty ABC",
    phone: "0912345678",
    address: "123 Đường Lê Lợi, Q.1, TP.HCM",
    region: "TP.HCM",
    productGroup: "Điện tử",
    requirements: "Cần giải pháp quản lý kho",
    consultant: "Nguyễn Văn A",
    zaloConsultant: "0912345678",
    advisor: "Nguyễn Văn A",
    customerSegment: "VIP",
    customerStatus: "ĐANG TƯ VẤN",
    email: "abc@company.com",
    createdDate: "2024-01-15",
    lastContact: "2024-11-05",
    birthday: "1990-03-20",
    status: [
      {
        key: "consulting",
        label: "ĐANG TƯ VẤN",
        bgColor: "#0E7490",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "2",
    customerId: "KH002",
    name: "Cửa hàng XYZ",
    phone: "0987654321",
    address: "456 Phố Tây, Ba Đình, Hà Nội",
    region: "Hà Nội",
    productGroup: "Thời trang",
    requirements: "Muốn mở rộng kinh doanh",
    consultant: "Trần Thị B",
    zaloConsultant: "0987654321",
    advisor: "Trần Thị B",
    customerSegment: "Thường xuyên",
    customerStatus: "ĐÃ GỬI BẢO GIÁ KHÁCH",
    email: "xyz@store.com",
    createdDate: "2024-02-10",
    lastContact: "2024-11-08",
    birthday: "1988-07-15",
    status: [
      {
        key: "sent_quote",
        label: "ĐÃ GỬI BẢO GIÁ KHÁCH",
        bgColor: "#22C55E",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "3",
    customerId: "KH003",
    name: "Bán buôn DEF",
    phone: "0901234567",
    address: "789 Đường Hàng Nón, Q.3, TP.HCM",
    region: "TP.HCM",
    productGroup: "Thực phẩm",
    requirements: "Tìm kiếm đối tác mới",
    consultant: "Phạm Văn C",
    zaloConsultant: "0901234567",
    advisor: "Phạm Văn C",
    customerSegment: "Mới",
    customerStatus: "LEAD MỚI",
    email: "def@wholesale.com",
    createdDate: "2024-03-05",
    lastContact: "2024-11-01",
    birthday: "1992-11-30",
    status: [
      {
        key: "new_lead",
        label: "LEAD MỚI",
        bgColor: "#EF4444",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "4",
    customerId: "KH004",
    name: "Công ty Nội thất GHI",
    phone: "0934567890",
    address: "321 Đường Kim Mã, Ba Đình, Hà Nội",
    region: "Hà Nội",
    productGroup: "Nội thất",
    requirements: "Cần tài chính hỗ trợ",
    consultant: "Hoàng Thị D",
    zaloConsultant: "0934567890",
    advisor: "Hoàng Thị D",
    customerSegment: "Tiềm năng",
    customerStatus: "ĐỢI KÈ TOÀN BẢO GIÁ",
    email: "ghi@furniture.com",
    createdDate: "2024-04-12",
    lastContact: "2024-11-03",
    birthday: "1985-05-22",
    status: [
      {
        key: "waiting_quote",
        label: "ĐỢI KÈ TOÀN BẢO GIÁ",
        bgColor: "#2563EB",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "5",
    customerId: "KH005",
    name: "Cửa hàng Công nghệ JKL",
    phone: "0945678901",
    address: "654 Đường Tôn Đức Thắng, Hải An, Hải Phòng",
    region: "Hải Phòng",
    productGroup: "Công nghệ",
    requirements: "Nâng cấp hệ thống",
    consultant: "Nguyễn Văn A",
    zaloConsultant: "0945678901",
    advisor: "Nguyễn Văn A",
    customerSegment: "VIP",
    customerStatus: "HOÀN THÀNH",
    email: "jkl@tech.com",
    createdDate: "2024-05-20",
    lastContact: "2024-11-07",
    birthday: "1989-09-14",
    status: [
      {
        key: "completed",
        label: "HOÀN THÀNH",
        bgColor: "#EF4444",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "6",
    customerId: "KH006",
    name: "Công ty Vận tải MNO",
    phone: "0978123456",
    address: "12 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    region: "Hà Nội",
    productGroup: "Logistics",
    requirements: "Tối ưu chi phí vận hành",
    consultant: "Phạm Minh H",
    zaloConsultant: "0978123456",
    advisor: "Phạm Minh H",
    customerSegment: "Doanh nghiệp",
    customerStatus: "CHỐT ĐƠN",
    email: "mno@logistics.com",
    createdDate: "2024-06-10",
    lastContact: "2024-11-09",
    birthday: "1987-04-10",
    status: [
      {
        key: "order_closed",
        label: "CHỐT ĐƠN",
        bgColor: "#DC2626",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "7",
    customerId: "KH007",
    name: "Nhà hàng SEA",
    phone: "0909888777",
    address: "89 Nguyễn Huệ, Q.1, TP.HCM",
    region: "TP.HCM",
    productGroup: "Nhà hàng",
    requirements: "Cần hệ thống đặt bàn tự động",
    consultant: "Trần Anh Q",
    zaloConsultant: "0909888777",
    advisor: "Trần Anh Q",
    customerSegment: "VIP",
    customerStatus: "KHÔNG CHỐT",
    email: "sea@restaurant.vn",
    createdDate: "2024-07-05",
    lastContact: "2024-11-06",
    birthday: "1991-12-02",
    status: [
      {
        key: "not_closed",
        label: "KHÔNG CHỐT",
        bgColor: "#FCD34D",
        textColor: "#92400E",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "8",
    customerId: "KH008",
    name: "Shop Thời trang PQR",
    phone: "0911999888",
    address: "23 Lý Thường Kiệt, Hải Phòng",
    region: "Hải Phòng",
    productGroup: "Thời trang",
    requirements: "Cần tích hợp CRM",
    consultant: "Vũ Thị T",
    zaloConsultant: "0911999888",
    advisor: "Vũ Thị T",
    customerSegment: "Thường xuyên",
    customerStatus: "KHÔNG LIÊN HỆ ĐƯỢC KHÁCH",
    email: "pqr@shop.vn",
    createdDate: "2024-08-01",
    lastContact: "2024-10-30",
    birthday: "1994-06-22",
    status: [
      {
        key: "cannot_contact",
        label: "KHÔNG LIÊN HỆ ĐƯỢC KHÁCH",
        bgColor: "#15803D",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "9",
    customerId: "KH009",
    name: "Công ty Dịch vụ TUV",
    phone: "0988222333",
    address: "100 Điện Biên Phủ, Đà Nẵng",
    region: "Đà Nẵng",
    productGroup: "Dịch vụ",
    requirements: "Cần đào tạo nhân sự bán hàng",
    consultant: "Nguyễn Thu N",
    zaloConsultant: "0988222333",
    advisor: "Nguyễn Thu N",
    customerSegment: "Mới",
    customerStatus: "KHÔNG CHỐT ĐƯỢC THÔNG SỐ",
    email: "tuv@service.com",
    createdDate: "2024-09-02",
    lastContact: "2024-11-04",
    birthday: "1993-09-10",
    status: [
      {
        key: "cannot_finalize",
        label: "KHÔNG CHỐT ĐƯỢC THÔNG SỐ",
        bgColor: "#1E3A8A",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "10",
    customerId: "KH010",
    name: "Studio Ảnh UVW",
    phone: "0909090909",
    address: "55 Nguyễn Công Trứ, Huế",
    region: "Huế",
    productGroup: "Dịch vụ chụp ảnh",
    requirements: "Muốn tự động hóa quy trình thanh toán",
    consultant: "Lê Văn P",
    zaloConsultant: "0909090909",
    advisor: "Lê Văn P",
    customerSegment: "Tiềm năng",
    customerStatus: "THIẾU THÔNG TIN",
    email: "uvw@studio.vn",
    createdDate: "2024-10-01",
    lastContact: "2024-11-11",
    birthday: "1995-11-11",
    status: [
      {
        key: "missing_info",
        label: "THIẾU THÔNG TIN",
        bgColor: "#FCD34D",
        textColor: "#92400E",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "11",
    customerId: "KH001",
    name: "Công Ty ABC",
    phone: "0912345678",
    address: "123 Đường Lê Lợi, Q.1, TP.HCM",
    region: "TP.HCM",
    productGroup: "Điện tử",
    requirements: "Cần giải pháp quản lý kho",
    consultant: "Nguyễn Văn A",
    zaloConsultant: "0912345678",
    advisor: "Nguyễn Văn A",
    customerSegment: "VIP",
    customerStatus: "ĐANG TƯ VẤN",
    email: "abc@company.com",
    createdDate: "2024-01-15",
    lastContact: "2024-11-05",
    birthday: "1990-03-20",
    status: [
      {
        key: "consulting",
        label: "ĐANG TƯ VẤN",
        bgColor: "#0E7490",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "12",
    customerId: "KH002",
    name: "Cửa hàng XYZ",
    phone: "0987654321",
    address: "456 Phố Tây, Ba Đình, Hà Nội",
    region: "Hà Nội",
    productGroup: "Thời trang",
    requirements: "Muốn mở rộng kinh doanh",
    consultant: "Trần Thị B",
    zaloConsultant: "0987654321",
    advisor: "Trần Thị B",
    customerSegment: "Thường xuyên",
    customerStatus: "ĐÃ GỬI BẢO GIÁ KHÁCH",
    email: "xyz@store.com",
    createdDate: "2024-02-10",
    lastContact: "2024-11-08",
    birthday: "1988-07-15",
    status: [
      {
        key: "sent_quote",
        label: "ĐÃ GỬI BẢO GIÁ KHÁCH",
        bgColor: "#22C55E",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "13",
    customerId: "KH003",
    name: "Bán buôn DEF",
    phone: "0901234567",
    address: "789 Đường Hàng Nón, Q.3, TP.HCM",
    region: "TP.HCM",
    productGroup: "Thực phẩm",
    requirements: "Tìm kiếm đối tác mới",
    consultant: "Phạm Văn C",
    zaloConsultant: "0901234567",
    advisor: "Phạm Văn C",
    customerSegment: "Mới",
    customerStatus: "LEAD MỚI",
    email: "def@wholesale.com",
    createdDate: "2024-03-05",
    lastContact: "2024-11-01",
    birthday: "1992-11-30",
    status: [
      {
        key: "new_lead",
        label: "LEAD MỚI",
        bgColor: "#EF4444",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "14",
    customerId: "KH004",
    name: "Công ty Nội thất GHI",
    phone: "0934567890",
    address: "321 Đường Kim Mã, Ba Đình, Hà Nội",
    region: "Hà Nội",
    productGroup: "Nội thất",
    requirements: "Cần tài chính hỗ trợ",
    consultant: "Hoàng Thị D",
    zaloConsultant: "0934567890",
    advisor: "Hoàng Thị D",
    customerSegment: "Tiềm năng",
    customerStatus: "ĐỢI KÈ TOÀN BẢO GIÁ",
    email: "ghi@furniture.com",
    createdDate: "2024-04-12",
    lastContact: "2024-11-03",
    birthday: "1985-05-22",
    status: [
      {
        key: "waiting_quote",
        label: "ĐỢI KÈ TOÀN BẢO GIÁ",
        bgColor: "#2563EB",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "15",
    customerId: "KH005",
    name: "Cửa hàng Công nghệ JKL",
    phone: "0945678901",
    address: "654 Đường Tôn Đức Thắng, Hải An, Hải Phòng",
    region: "Hải Phòng",
    productGroup: "Công nghệ",
    requirements: "Nâng cấp hệ thống",
    consultant: "Nguyễn Văn A",
    zaloConsultant: "0945678901",
    advisor: "Nguyễn Văn A",
    customerSegment: "VIP",
    customerStatus: "HOÀN THÀNH",
    email: "jkl@tech.com",
    createdDate: "2024-05-20",
    lastContact: "2024-11-07",
    birthday: "1989-09-14",
    status: [
      {
        key: "completed",
        label: "HOÀN THÀNH",
        bgColor: "#EF4444",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "16",
    customerId: "KH006",
    name: "Công ty Vận tải MNO",
    phone: "0978123456",
    address: "12 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    region: "Hà Nội",
    productGroup: "Logistics",
    requirements: "Tối ưu chi phí vận hành",
    consultant: "Phạm Minh H",
    zaloConsultant: "0978123456",
    advisor: "Phạm Minh H",
    customerSegment: "Doanh nghiệp",
    customerStatus: "CHỐT ĐƠN",
    email: "mno@logistics.com",
    createdDate: "2024-06-10",
    lastContact: "2024-11-09",
    birthday: "1987-04-10",
    status: [
      {
        key: "order_closed",
        label: "CHỐT ĐƠN",
        bgColor: "#DC2626",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "17",
    customerId: "KH007",
    name: "Nhà hàng SEA",
    phone: "0909888777",
    address: "89 Nguyễn Huệ, Q.1, TP.HCM",
    region: "TP.HCM",
    productGroup: "Nhà hàng",
    requirements: "Cần hệ thống đặt bàn tự động",
    consultant: "Trần Anh Q",
    zaloConsultant: "0909888777",
    advisor: "Trần Anh Q",
    customerSegment: "VIP",
    customerStatus: "KHÔNG CHỐT",
    email: "sea@restaurant.vn",
    createdDate: "2024-07-05",
    lastContact: "2024-11-06",
    birthday: "1991-12-02",
    status: [
      {
        key: "not_closed",
        label: "KHÔNG CHỐT",
        bgColor: "#FCD34D",
        textColor: "#92400E",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "18",
    customerId: "KH008",
    name: "Shop Thời trang PQR",
    phone: "0911999888",
    address: "23 Lý Thường Kiệt, Hải Phòng",
    region: "Hải Phòng",
    productGroup: "Thời trang",
    requirements: "Cần tích hợp CRM",
    consultant: "Vũ Thị T",
    zaloConsultant: "0911999888",
    advisor: "Vũ Thị T",
    customerSegment: "Thường xuyên",
    customerStatus: "KHÔNG LIÊN HỆ ĐƯỢC KHÁCH",
    email: "pqr@shop.vn",
    createdDate: "2024-08-01",
    lastContact: "2024-10-30",
    birthday: "1994-06-22",
    status: [
      {
        key: "cannot_contact",
        label: "KHÔNG LIÊN HỆ ĐƯỢC KHÁCH",
        bgColor: "#15803D",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "19",
    customerId: "KH009",
    name: "Công ty Dịch vụ TUV",
    phone: "0988222333",
    address: "100 Điện Biên Phủ, Đà Nẵng",
    region: "Đà Nẵng",
    productGroup: "Dịch vụ",
    requirements: "Cần đào tạo nhân sự bán hàng",
    consultant: "Nguyễn Thu N",
    zaloConsultant: "0988222333",
    advisor: "Nguyễn Thu N",
    customerSegment: "Mới",
    customerStatus: "KHÔNG CHỐT ĐƯỢC THÔNG SỐ",
    email: "tuv@service.com",
    createdDate: "2024-09-02",
    lastContact: "2024-11-04",
    birthday: "1993-09-10",
    status: [
      {
        key: "cannot_finalize",
        label: "KHÔNG CHỐT ĐƯỢC THÔNG SỐ",
        bgColor: "#1E3A8A",
        textColor: "#FFFFFF",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
  {
    id: "20",
    customerId: "KH010",
    name: "Studio Ảnh UVW",
    phone: "0909090909",
    address: "55 Nguyễn Công Trứ, Huế",
    region: "Huế",
    productGroup: "Dịch vụ chụp ảnh",
    requirements: "Muốn tự động hóa quy trình thanh toán",
    consultant: "Lê Văn P",
    zaloConsultant: "0909090909",
    advisor: "Lê Văn P",
    customerSegment: "Tiềm năng",
    customerStatus: "THIẾU THÔNG TIN",
    email: "uvw@studio.vn",
    createdDate: "2024-10-01",
    lastContact: "2024-11-11",
    birthday: "1995-11-11",
    status: [
      {
        key: "missing_info",
        label: "THIẾU THÔNG TIN",
        bgColor: "#FCD34D",
        textColor: "#92400E",
      },
    ],
    avatarUrl: undefined,
    website: "",
    taxCode: "",
    lastPurchase: "",
  },
];

export const STATUS_CONFIG: Record<
  CustomerStatusType,
  { label: string; bgColor: string; textColor: string }
> = {
  missing_info: {
    label: "THIẾU THÔNG TIN",
    bgColor: "#FCD34D",
    textColor: "#92400E",
  },
  completed: { label: "HOÀN THÀNH", bgColor: "#EF4444", textColor: "#FFFFFF" },
  new_lead: { label: "LEAD MỚI", bgColor: "#EF4444", textColor: "#FFFFFF" },
  cannot_finalize: {
    label: "KHÔNG CHỐT ĐƯỢC THÔNG SỐ",
    bgColor: "#1E3A8A",
    textColor: "#FFFFFF",
  },
  consulting: {
    label: "ĐANG TƯ VẤN",
    bgColor: "#0E7490",
    textColor: "#FFFFFF",
  },
  waiting_quote: {
    label: "ĐỢI KÈ TOÀN BẢO GIÁ",
    bgColor: "#2563EB",
    textColor: "#FFFFFF",
  },
  sent_quote: {
    label: "ĐÃ GỬI BẢO GIÁ KHÁCH",
    bgColor: "#22C55E",
    textColor: "#FFFFFF",
  },
  order_closed: { label: "CHỐT ĐƠN", bgColor: "#DC2626", textColor: "#FFFFFF" },
  not_closed: { label: "KHÔNG CHỐT", bgColor: "#FCD34D", textColor: "#92400E" },
  cannot_contact: {
    label: "KHÔNG LIÊN HỆ ĐƯỢC KHÁCH",
    bgColor: "#15803D",
    textColor: "#FFFFFF",
  },
};

export const MOCK_CUSTOMERS = DEFAULT_CUSTOMERS;
